[build]
  base    = "portfolio-react"
  command = "npm install && node node_modules/vite/bin/vite.js build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
